channel_buffer_size = 100000

[write]
  concurrency = 10
  batch_size = 10000
  batch_interval = "0s"
  database = "stress"
  precision = "s"
  address = "localhost:8086"
  reset_database = true
  start_date = "Jan 2, 2006 at 3:04pm (MST)"

[[series]]
  tick = "5s"
  jitter = true
  point_count = 10000 # number of points that will be written for each of the series
  measurement = "cpu"
  series_count = 10000

 # tag_count = 20 # number of "generic" tags on a series (e.g. tag-key-1=tag-value, ... ,tag-key-20=tag-value)

  [[series.tag]]
    key = "host"
    value = "idk"

  [[series.tag]]
    key = "location"
    value = "lame"

  [[series.field]]
    key = "value"
    type = "float64"


